<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = [
			['prefix' => 'US', 'name' => 'United States'],
			['prefix' => 'CA', 'name' => 'Canada'],
			['prefix' => 'AF', 'name' => 'Afghanistan'],
			['prefix' => 'AL', 'name' => 'Albania'],
			['prefix' => 'DZ', 'name' => 'Algeria'],
			['prefix' => 'AS', 'name' => 'American Samoa'],
			['prefix' => 'AD', 'name' => 'Andorra'],
			['prefix' => 'AO', 'name' => 'Angola'],
			['prefix' => 'AI', 'name' => 'Anguilla'],
			['prefix' => 'AG', 'name' => 'Antigua and Barbuda'],
			['prefix' => 'AR', 'name' => 'Argentina'],
			['prefix' => 'AM', 'name' => 'Armenia'],
			['prefix' => 'AW', 'name' => 'Aruba'],
			['prefix' => 'AU', 'name' => 'Australia'],
			['prefix' => 'AT', 'name' => 'Austria'],
			['prefix' => 'AZ', 'name' => 'Azerbaijan'],
			['prefix' => 'BS', 'name' => 'Bahamas'],
			['prefix' => 'BH', 'name' => 'Bahrain'],
			['prefix' => 'BD', 'name' => 'Bangladesh'],
			['prefix' => 'BB', 'name' => 'Barbados'],
			['prefix' => 'BY', 'name' => 'Belarus'],
			['prefix' => 'BE', 'name' => 'Belgium'],
			['prefix' => 'BZ', 'name' => 'Belize'],
			['prefix' => 'BJ', 'name' => 'Benin'],
			['prefix' => 'BM', 'name' => 'Bermuda'],
			['prefix' => 'BT', 'name' => 'Bhutan'],
			['prefix' => 'BO', 'name' => 'Bolivia'],
			['prefix' => 'BA', 'name' => 'Bosnia and Herzegovina'],
			['prefix' => 'BW', 'name' => 'Botswana'],
			['prefix' => 'BR', 'name' => 'Brazil'],
			['prefix' => 'BN', 'name' => 'Brunei Darussalam'],
			['prefix' => 'BG', 'name' => 'Bulgaria'],
			['prefix' => 'BF', 'name' => 'Burkina Faso'],
			['prefix' => 'BI', 'name' => 'Burundi'],
			['prefix' => 'KH', 'name' => 'Cambodia'],
			['prefix' => 'CM', 'name' => 'Cameroon'],
			['prefix' => 'CV', 'name' => 'Cape Verde'],
			['prefix' => 'KY', 'name' => 'Cayman Islands'],
			['prefix' => 'CF', 'name' => 'Central African Republic'],
			['prefix' => 'TD', 'name' => 'Chad'],
			['prefix' => 'CL', 'name' => 'Chile'],
			['prefix' => 'CN', 'name' => 'China'],
			['prefix' => 'CX', 'name' => 'Christmas Island'],
			['prefix' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
			['prefix' => 'CO', 'name' => 'Colombia'],
			['prefix' => 'KM', 'name' => 'Comoros'],
			['prefix' => 'CG', 'name' => 'Congo'],
            ['prefix' => 'CK', 'name' => 'Cook Islands'],
            ['prefix' => 'CR', 'name' => 'Costa Rica'],
			['prefix' => 'HR', 'name' => 'Croatia'],
			['prefix' => 'CU', 'name' => 'Cuba'],
			['prefix' => 'CY', 'name' => 'Cyprus'],
			['prefix' => 'CZ', 'name' => 'Czech Republic'],
			['prefix' => 'CD', 'name' => 'Democratic Republic of Congo'],
			['prefix' => 'DK', 'name' => 'Denmark'],
			['prefix' => 'DJ', 'name' => 'Djibouti'],
			['prefix' => 'DM', 'name' => 'Dominica'],
			['prefix' => 'DO', 'name' => 'Dominican Republic'],
			['prefix' => 'TP', 'name' => 'East Timor'],
            ['prefix' => 'EC', 'name' => 'Ecudaor'],
            ['prefix' => 'EG', 'name' => 'Egypt'],
			['prefix' => 'SV', 'name' => 'El Salvador'],
			['prefix' => 'GQ', 'name' => 'Equatorial Guinea'],
			['prefix' => 'ER', 'name' => 'Eritrea'],
			['prefix' => 'EE', 'name' => 'Estonia'],
			['prefix' => 'ET', 'name' => 'Ethiopia'],
			['prefix' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
            ['prefix' => 'FO', 'name' => 'Faroe Islands'],
            ['prefix' => 'FJ', 'name' => 'Fiji'],
			['prefix' => 'FI', 'name' => 'Finland'],
			['prefix' => 'FR', 'name' => 'France'],
            ['prefix' => 'FX', 'name' => 'France, Metropolitan'],
            ['prefix' => 'GF', 'name' => 'French Guiana'],
			['prefix' => 'PF', 'name' => 'French Polynesia'],
			['prefix' => 'GA', 'name' => 'Gabon'],
			['prefix' => 'GM', 'name' => 'Gambia'],
			['prefix' => 'GE', 'name' => 'Georgia'],
			['prefix' => 'DE', 'name' => 'Germany'],
			['prefix' => 'GH', 'name' => 'Ghana'],
			['prefix' => 'GI', 'name' => 'Gibraltar'],
			['prefix' => 'GR', 'name' => 'Greece'],
			['prefix' => 'GL', 'name' => 'Greenland'],
			['prefix' => 'GD', 'name' => 'Grenada'],
			['prefix' => 'GP', 'name' => 'Guadeloupe'],
			['prefix' => 'GU', 'name' => 'Guam'],
			['prefix' => 'GT', 'name' => 'Guatemala'],
			['prefix' => 'GN', 'name' => 'Guinea'],
			['prefix' => 'GW', 'name' => 'Guinea-Bissau'],
			['prefix' => 'GY', 'name' => 'Guyana'],
			['prefix' => 'HT', 'name' => 'Haiti'],
			['prefix' => 'HN', 'name' => 'Honduras'],
			['prefix' => 'HK', 'name' => 'Hong Kong'],
			['prefix' => 'HU', 'name' => 'Hungary'],
			['prefix' => 'IS', 'name' => 'Iceland'],
			['prefix' => 'IN', 'name' => 'India'],
			['prefix' => 'ID', 'name' => 'Indonesia'],
			['prefix' => 'IR', 'name' => 'Iran'],
			['prefix' => 'IQ', 'name' => 'Iraq'],
			['prefix' => 'IE', 'name' => 'Ireland'],
			['prefix' => 'IL', 'name' => 'Israel'],
			['prefix' => 'IT', 'name' => 'Italy'],
			['prefix' => 'JM', 'name' => 'Jamaica'],
			['prefix' => 'JP', 'name' => 'Japan'],
			['prefix' => 'JO', 'name' => 'Jordan'],
			['prefix' => 'KZ', 'name' => 'Kazakhstan'],
			['prefix' => 'KE', 'name' => 'Kenya'],
			['prefix' => 'KI', 'name' => 'Kiribati'],
			['prefix' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
			['prefix' => 'KR', 'name' => 'Korea, Republic of'],
			['prefix' => 'KW', 'name' => 'Kuwait'],
			['prefix' => 'KG', 'name' => 'Kyrgyzstan'],
			['prefix' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
			['prefix' => 'LV', 'name' => 'Latvia'],
			['prefix' => 'LB', 'name' => 'Lebanon'],
			['prefix' => 'LS', 'name' => 'Lesotho'],
			['prefix' => 'LR', 'name' => 'Liberia'],
			['prefix' => 'LY', 'name' => 'Libyan'],
			['prefix' => 'LI', 'name' => 'Liechtenstein'],
			['prefix' => 'LT', 'name' => 'Lithuania'],
			['prefix' => 'LU', 'name' => 'Luxembourg'],
			['prefix' => 'MO', 'name' => 'Macau'],
			['prefix' => 'MK', 'name' => 'Macedonia'],
			['prefix' => 'MG', 'name' => 'Madagascar'],
			['prefix' => 'MW', 'name' => 'Malawi'],
			['prefix' => 'MY', 'name' => 'Malaysia'],
			['prefix' => 'MV', 'name' => 'Maldives'],
			['prefix' => 'ML', 'name' => 'Mali'],
			['prefix' => 'MT', 'name' => 'Malta'],
			['prefix' => 'MH', 'name' => 'Marshall Islands'],
			['prefix' => 'MQ', 'name' => 'Martinique'],
			['prefix' => 'MR', 'name' => 'Mauritania'],
			['prefix' => 'MU', 'name' => 'Mauritius'],
			['prefix' => 'TY', 'name' => 'Mayotte'],
			['prefix' => 'MX', 'name' => 'Mexico'],
			['prefix' => 'FM', 'name' => 'Micronesia'],
			['prefix' => 'MD', 'name' => 'Moldova'],
			['prefix' => 'MC', 'name' => 'Monaco'],
			['prefix' => 'MN', 'name' => 'Mongolia'],
			['prefix' => 'MS', 'name' => 'Montserrat'],
			['prefix' => 'MA', 'name' => 'Morocco'],
			['prefix' => 'MZ', 'name' => 'Mozambique'],
			['prefix' => 'MM', 'name' => 'Myanmar'],
			['prefix' => 'NA', 'name' => 'Namibia'],
			['prefix' => 'NR', 'name' => 'Nauru'],
			['prefix' => 'NP', 'name' => 'Nepal'],
			['prefix' => 'NL', 'name' => 'Netherlands'],
			['prefix' => 'NC', 'name' => 'New Caledonia'],
			['prefix' => 'NZ', 'name' => 'New Zealand'],
			['prefix' => 'NI', 'name' => 'Nicaragua'],
			['prefix' => 'NE', 'name' => 'Niger'],
			['prefix' => 'NG', 'name' => 'Nigeria'],
			['prefix' => 'NU', 'name' => 'Niue'],
			['prefix' => 'NF', 'name' => 'Norfork Island'],
			['prefix' => 'MP', 'name' => 'Northern Mariana Islands'],
			['prefix' => 'NO', 'name' => 'Norway'],
			['prefix' => 'OM', 'name' => 'Oman'],
			['prefix' => 'PK', 'name' => 'Pakistan'],
			['prefix' => 'PW', 'name' => 'Palau'],
			['prefix' => 'PA', 'name' => 'Panama'],
			['prefix' => 'PG', 'name' => 'Papua New Guinea'],
			['prefix' => 'PY', 'name' => 'Paraguay'],
			['prefix' => 'PE', 'name' => 'Peru'],
			['prefix' => 'PH', 'name' => 'Philippines'],
			['prefix' => 'PN', 'name' => 'Pitcairn'],
			['prefix' => 'PL', 'name' => 'Poland'],
			['prefix' => 'PT', 'name' => 'Portugal'],
			['prefix' => 'PR', 'name' => 'Puerto Rico'],
			['prefix' => 'QA', 'name' => 'Qatar'],
			['prefix' => 'SS', 'name' => 'Republic of South Sudan'],
			['prefix' => 'RE', 'name' => 'Reunion'],
			['prefix' => 'RO', 'name' => 'Romania'],
			['prefix' => 'RU', 'name' => 'Russian Federation'],
			['prefix' => 'RW', 'name' => 'Rwanda'],
			['prefix' => 'KN', 'name' => 'Saint Kitts and Nevis'],
			['prefix' => 'LC', 'name' => 'Saint Lucia'],
			['prefix' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
			['prefix' => 'WS', 'name' => 'Samoa'],
			['prefix' => 'SM', 'name' => 'San Marino'],
			['prefix' => 'ST', 'name' => 'Sao Tome and Principe'],
			['prefix' => 'SA', 'name' => 'Saudi Arabia'],
			['prefix' => 'SN', 'name' => 'Senegal'],
			['prefix' => 'RS', 'name' => 'Serbia'],
			['prefix' => 'SC', 'name' => 'Seychelles'],
			['prefix' => 'SL', 'name' => 'Sierra Leone'],
			['prefix' => 'SG', 'name' => 'Singapore'],
			['prefix' => 'SK', 'name' => 'Slovakia'],
			['prefix' => 'SI', 'name' => 'Slovenia'],
			['prefix' => 'SB', 'name' => 'Solomon Islands'],
			['prefix' => 'SO', 'name' => 'Somalia'],
			['prefix' => 'ZA', 'name' => 'South Africa'],
			['prefix' => 'GS', 'name' => 'South Georgia South Sandwich Islands'],
			['prefix' => 'ES', 'name' => 'Spain'],
			['prefix' => 'LK', 'name' => 'Sri Lanka'],
			['prefix' => 'SH', 'name' => 'Saint Helena'],
			['prefix' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
			['prefix' => 'SD', 'name' => 'Sudan'],
			['prefix' => 'SR', 'name' => 'Suriname'],
			['prefix' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands'],
			['prefix' => 'SZ', 'name' => 'Swaziland'],
			['prefix' => 'SE', 'name' => 'Sweden'],
			['prefix' => 'CH', 'name' => 'Switzerland'],
			['prefix' => 'SY', 'name' => 'Syrian Arab Republic'],
			['prefix' => 'TW', 'name' => 'Taiwan'],
			['prefix' => 'TJ', 'name' => 'Tajikistan'],
			['prefix' => 'TZ', 'name' => 'Tanzania'],
			['prefix' => 'TH', 'name' => 'Thailand'],
			['prefix' => 'TG', 'name' => 'Togo'],
			['prefix' => 'TK', 'name' => 'Tokelau'],
			['prefix' => 'TO', 'name' => 'Tonga'],
			['prefix' => 'TT', 'name' => 'Trinidad and Tobago'],
			['prefix' => 'TN', 'name' => 'Tunisia'],
			['prefix' => 'TR', 'name' => 'Turkey'],
			['prefix' => 'TM', 'name' => 'Turkmenistan'],
			['prefix' => 'TC', 'name' => 'Turks and Caicos Islands'],
			['prefix' => 'TV', 'name' => 'Tuvalu'],
			['prefix' => 'UG', 'name' => 'Uganda'],
			['prefix' => 'UA', 'name' => 'Ukraine'],
			['prefix' => 'AE', 'name' => 'United Arab Emirates'],
			['prefix' => 'GB', 'name' => 'United Kingdom'],
			['prefix' => 'UY', 'name' => 'Uruguay'],
			['prefix' => 'UZ', 'name' => 'Uzbekistan'],
			['prefix' => 'VU', 'name' => 'Vanuatu'],
			['prefix' => 'VA', 'name' => 'Vatican City State'],
			['prefix' => 'VE', 'name' => 'Venezuela'],
			['prefix' => 'VN', 'name' => 'Vietnam'],
			['prefix' => 'YE', 'name' => 'Yemen'],
            ['prefix' => 'YU', 'name' => 'Yugoslavia'],
            ['prefix' => 'ZR', 'name' => 'Zaire'],
            ['prefix' => 'ZM', 'name' => 'Zambia'],
			['prefix' => 'ZW', 'name' => 'Zimbabwe'],
        ];

		DB::table('countries')->insert($countries);

    }
}
